#!/bin/ash

SEARCH='hackpgh OR hackpittsburgh OR "hack pittsburgh"'
LED_SIGN=/dev/tts/1

wget -q -O - "http://search.twitter.com/search.json?show_user=true&rpp=1&q=$SEARCH" |  sed -e 's/^.*"from_user":"\([^"]*\)".*"text":"\([^"]*\)".*/\1: \2?/' > $LED_SIGN

